### ISSUE TITLE
Updated PhpStorm Code Style

### ISSUE THREAD

**Issue by raamdev** [websharks/phpstorm#3]
@jaswsinc you shared [a tweaked version](https://cloudup.com/c2ZbZls0ZEa) of the PhpStorm code style in https://github.com/websharks/comment-mail-pro/pull/58#issuecomment-184173787. I installed it and tried reformatting the files in your `comment-mail-pro/feature/150` branch (no changes would mean our styles match). However, there were a bunch of slight differences when I ran the reformatter. 

The most common one that I found was this:

```php
(string) $property;
```

becomes this when I run the PhpStorm reformatter (the space is removed):

```php
(string)$property;
```

There were a couple of other minor differences, but I'd rather take this one step at a time. 

Did you run the PhpStorm reformatter after you updated the code style to see if there were differences in what you're using with Atom?

---

I did try running the PHP CS Fixer on the file to see if that would revert the file back to what you had committed, but it did not. I also ran the PHP Code Sniffer, which passed fine. 

Any idea what's going on here?

**Comment by raamdev** [comment]
I've narrowed down the bulk of the changes that result from reformatting the `comment-mail-pro/feature/150` branch to the two PhpStorm Code Style settings below. I've included the value of the setting as defined in [the tweaked code style](https://cloudup.com/c2ZbZls0ZEa), along with before and after examples that result in changes.

### Space after typecast = disabled

This:

```php
(string) $property;
```

Gets changed to this:

```php
(string)$property;
```

### Align consecutive assignments = enabled

This: 

```php
$default_args = [
    'ns_id_suffix'   => '',
    'ns_name_suffix' => '',
    'class_prefix'   => '',
];
$args = array_merge($default_args, $args);
$args = array_intersect_key($args, $default_args);
```

Get changed to this:

```php
$default_args = [
    'ns_id_suffix'   => '',
    'ns_name_suffix' => '',
    'class_prefix'   => '',
];
$args         = array_merge($default_args, $args);
$args         = array_intersect_key($args, $default_args);
```

---

The Space after typecast setting is easy to fix, but the Align consecutive assignments issue appears to occur because of how PhpStorm considers all lines directly above and below until it finds a blank line.

**Comment by raamdev** [comment]
@jaswsinc I'm fine with not making a big deal out of these code style issues if you are. :-) I don't plan to be running a project-wide reformatting anyway--any reformatting I do is almost always reformatting a selection of code that I'm working on. Issues like these will only be a big deal if one of us is constantly reformatting the entire codebase.

**Comment by jaswsinc** [comment]
I used PHP CS Fixer to format.

> I'm fine with not making a big deal out of these code style issues if you are. :-) 

Sounds good to me also. As long as we all can pass PHP Code Sniffer tests I think that's good enough. My experience with PHP Code Sniffer has been quite good. It catches everything that's important. Anything it doesn't catch can slip by as far as I'm concerned also.

Having said that, the closer we can get PhpStorm to PHP CS Fixer the better; i.e., fewer formatting differences between those of us using one or other. Since PhpStorm is easier to configure and manipulate, if you find that you can tweak those formatter settings and make them match-up that'd be great. Ideally, Renz or Kristine would able to just press a button to run PhpStorm formatting or PHP CS Fixer and reformat an entire file if they need to.

**Comment by raamdev** [comment]
> Having said that, the closer we can get PhpStorm to PHP CS Fixer the better;

I ran PHP CS Fixer on the file that was changed by PhpStorm's formatter and it _did not revert the change_. I would be fine with just running PHP CS Fixer on my code to keep us in sync, but it appears that's not enough (i.e., Git will still report formatting differences between us).

```
/usr/local/bin/php-cs-fixer --level=psr2 --verbose fix /Users/raam/Projects/comment-mail-pro/src/includes/classes/ChartData.php
.
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
Fixed all files in 0.090 seconds, 5.500 MB memory used

Process finished with exit code 0
```

**Comment by jaswsinc** [comment]
Did you run it with this config file?
https://github.com/websharks/dotfiles/blob/000000-dev/.php_cs

**Comment by raamdev** [comment]
> Did you run it with this config file?

Yes. Even tried specifying `--config-file=/Users/raam/.php_cs` to make sure it was using the config.

**Comment by jaswsinc** [comment]
Thanks. Did you also try removing `--level=psr2` and just let the config file apply?

Can you give me an example of something that is not being changed as you expect?

**Comment by raamdev** [comment]
@jaswsinc Removing `--level=psr2` resulted in something different:

```
$ /usr/local/bin/php-cs-fixer --config-file=/Users/raam/.php_cs --verbose fix /Users/raam/Projects/comment-mail-pro/src/includes/classes/ChartData.php
Loaded config from "/Users/raam/.php_cs"
F
Legend: ?-unknown, I-invalid file syntax, file ignored, .-no changes, F-fixed, E-error
   1) /Users/raam/Projects/comment-mail-pro/src/includes/classes/ChartData.php (unalign_equals, phpdoc_type_to_var, unalign_double_arrow, phpdoc_var_to_type, align_equals, align_double_arrow)
```

> Can you give me an example of something that is not being changed as you expect?

Well, I'm going by what you said earlier:

> I used PHP CS Fixer to format.

So that would indicate to me that if we both use PHP CS Fixer with the same config file, we should both end up with the same formatting, correct?

That does not appear to be happening. For example, I formatted `ChartData.php` with PhpStorm (which changes the code format that you committed, thereby leaving us with the issue that our formats are out of sync). Here are the differences after formatting with PhpStorm (using the updated PhpStorm style you supplied earlier--but that's irrelevant, since our goal here is to reformat with PHP CS Fixer):

![2016-02-19_13-58-19](https://cloud.githubusercontent.com/assets/53005/13185770/db720d44-d710-11e5-8556-9bb124d3ccbb.png)

Now, if I run PHP CS Fixer on that file (in attempt to 'undo' the changes that PhpStorm's formatter made and instead make the format identical to the original), the differences change, but there are still differences:

![2016-02-19_14-00-20](https://cloud.githubusercontent.com/assets/53005/13185827/3f40c07c-d711-11e5-9700-3904b9845017.png)

**Comment by jaswsinc** [comment]
> Loaded config from "/Users/raam/.php_cs"

Great! :-) Removing the level override did the trick then; i.e., that allows the config file to load up.

> Now, if I run PHP CS Fixer on that file (in attempt to 'undo' the changes that PhpStorm's formatter made and instead make the format identical to the original), the differences change, but there are still differences:

Cool. That seems pretty close. If we can get the two just a bit closer it'd be great. Otherwise, I'd just stick with PHP CS Fixer instead of PhpStorm for now. It's more portable. The PhpStorm formatter is awesome. The only problem is that it's tied into that specific IDE, whereas PHP CS Fixer is a command-line tool that any of us can run.

**Comment by raamdev** [comment]
> I'd just stick with PHP CS Fixer instead of PhpStorm for now. It's more portable. The PhpStorm formatter is awesome. The only problem is that it's tied into that specific IDE, whereas PHP CS Fixer is a command-line tool that any of us can run.

I have no problem sticking with PHP CS Fixer. In fact, that's what all of this is about: I WANT to use PHP CS Fixer and just not use the PhpStorm formatter. But how can I do that if it's not going to reformat things  consistently? 

If I changed a file in the same way that the PhpStorm Formatter changed it as seen above, and then I ran the PHP CS Fixer to reformat the code with the intention of maintaining consistency between developers, I would execpt PHP CS Fixer to reformat the code to match the format everybody else is using. But what I showed above clearly demonstrates that it does not.

Running PHP CS Fixer is not reformatting the code to match the format that you committed, which is the whole point of a team agreeing to use the same code formatter (so that we're not unnecessarily committing style changes).

**Comment by jaswsinc** [comment]
I understand. The PHP CS Fixer is not perfect like PhpStorm is. As I noted before, it sometimes leaves certain things unchanged on me too. Overall, it doesn't have the power that PhpStorm does, when it comes to format styling. If you can find a better alternative I'd love to try it out. PHP CS Fixer is the best I have seen in terms of what is globally accessible as a CLI tool and capable of also being run on a server.

Hopefully, PhpStorm will release a CLI tool with their formatter soon. That'd be awesome. Until then, some of the more dramatic changes in indentation or reorganization of the code are not handled properly in all cases by PHP CS Fixer for some reason. In practice though, I have found that not to be a huge issue. If we all follow a known set of standards, then using PHP CS Fixer is about fixing minor flaws (which it does fine with), not so much about huge issues (which it sometimes fails on).

Still, I agree, there is _much_ room for improvement. I really wish there was a better option available. Ideally, the PhpStorm formatter would become available as an external tool. It has the best formatter of any that I've used over the years. It's nearly perfect in every way, and they continue to enhance it with each new release of the software.

**Comment by raamdev** [comment]
Maybe we should all switch back to PhpStorm. :stuck_out_tongue_winking_eye: 

---

I'll set up PHP CS Fixer as an external tool in PhpStorm and start using that whenever I need to reformat an entire file. :-) It doesn't happen often anyway. I'll also update this `websharks/phpstorm` repo with the modified code style that better matches PHP CS Fixer as I demonstrated above.

**Comment by jaswrks** [comment]
> Maybe we should all switch back to PhpStorm

Ha. I have nothing against PhpStorm really. However, I am happy with Atom for the moment also, even if it means I can't use their awesome formatter. Also, it's worth noting that PHP CS Fixer can do some things that PhpStorm does not, in terms of maintaining standards compliance. http://cs.sensiolabs.org/

The only problem I have with it is that it's not _also_ focused on styling.

**Comment by raamdev** [comment]
> The only problem I have with it is that it's not also focused on styling.

It's open-source, so you could [contribute](https://github.com/FriendsOfPhp/php-cs-fixer/blob/master/CONTRIBUTING.md) to lead a focus in project on styling. :-)

**Comment by jaswrks** [comment]
Good idea. I might just do that one of these days.
